# External gems
gems: [jekyll-archives, jekyll-sitemap, bourbon, neat, bitters, refills, font-awesome-less, highlight_js-rails, lightbox2-rails]
#  - jekyll-archives # Sorry, not GitHub pages friendly!
#  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Jeffrey Steven Bruce
subtitle: "Ain't No Time For The Present"
email: jeffbruce@gmail.com
name: Jeff Bruce
description: > 
  Jeff Bruce's personal website.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/jeffbruce" # the subpath of your site, e.g. /blog/
url: "http://jeffbruce.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives: 
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: jeffbruce

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
social:
  - name: Twitter
    icon: twitter
    username: jeffstevebruce
    url: https://twitter.com/jeffstevebruce
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: jeffstevebruce
    url: https://www.facebook.com/jeffstevebruce
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: jeffbruce
    url: https://github.com/jeffbruce
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Jeff Bruce
    url: https://ca.linkedin.com/in/brucejeff
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username: 
    url: 
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username: jeffstevebruce 
    url: https://soundcloud.com/jeffstevebruce
    desc: Follow me on SoundCloud
    share: true

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
